FROM amalgam8/a8-sidecar:0.1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y -q --no-install-recommends \
   python2.7 python-pip python-dev
   
RUN pip install Flask

RUN mkdir -p /opt/microservices
ADD app.py /opt/microservices/
EXPOSE 5000
WORKDIR /opt/microservices

ENTRYPOINT ["a8sidecar", "--proxy=false", "--log=false", "--supervise", "python", "-u", "app.py"]
